### Извлекаем данные по условиям

In [1]:
import pandas as pd

In [2]:
football = pd.read_csv("data_sf.csv")
football.describe()

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,12897.000000,12897.000000,1.289700e+04,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,...,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000
mean,6605.040862,24.795379,2.112449e+06,7517.562224,47.076374,42.876328,50.202528,56.026983,40.295030,52.461735,...,46.459874,55.942932,45.655811,46.186710,44.386679,17.218345,16.962317,16.797938,16.950221,17.315965
std,3782.545526,4.872212,6.498424e+06,23061.985387,18.043470,19.096935,17.281593,14.740436,17.080687,18.871643,...,15.479313,11.280631,19.456346,21.172586,20.726546,18.085618,17.349624,16.971411,17.369297,18.335817
min,0.000000,16.000000,0.000000e+00,1000.000000,5.000000,2.000000,4.000000,7.000000,4.000000,4.000000,...,5.000000,12.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3357.000000,21.000000,2.500000e+05,1000.000000,35.000000,28.000000,43.000000,50.000000,28.000000,45.000000,...,37.000000,49.000000,29.000000,25.000000,23.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,6622.000000,24.000000,5.000000e+05,2000.000000,51.000000,45.000000,54.000000,60.000000,41.000000,58.000000,...,47.000000,56.000000,51.000000,54.000000,51.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,9876.000000,28.000000,8.500000e+05,4000.000000,61.000000,59.000000,62.000000,65.000000,53.000000,65.000000,...,58.000000,63.000000,62.000000,64.000000,62.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,13125.000000,45.000000,1.185000e+08,565000.000000,93.000000,95.000000,94.000000,93.000000,90.000000,97.000000,...,91.000000,96.000000,93.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [3]:
football[football.Age > 20] # access the values using certain criteria

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
2,2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW,79,87,...,81,94,27,24,33,9,9,15,15,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
4,4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM,93,82,...,79,88,68,58,51,15,13,5,10,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12838,13067,D. Mackay,21,Scotland,Kilmarnock,30000,1000,GK,14,20,...,24,30,12,18,18,48,50,47,48,48
12857,13086,Wu Lei,21,China PR,Tianjin Quanjian FC,9000000,2000,LDM,52,29,...,46,39,52,40,49,8,15,11,8,5
12861,13090,Y. Uchimura,33,Japan,Hokkaido Consadole Sapporo,20000,1000,CAM,51,31,...,33,62,45,48,42,13,15,7,15,15
12870,13099,M. Hurst,22,Scotland,St. Johnstone FC,40000,1000,GK,19,15,...,29,28,12,15,16,45,49,50,50,45
12873,13102,K. Pilkington,44,England,Cambridge United,0,1000,GK,11,12,...,22,56,15,15,13,45,48,44,49,46

In [4]:
football[football.Age > football.Age.mean()] 
# print only those football players whos age more than avg

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
2,2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW,79,87,...,81,94,27,24,33,9,9,15,15,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
4,4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM,93,82,...,79,88,68,58,51,15,13,5,10,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12746,12975,Teng Shangkun,27,China PR,Tianjin TEDA FC,20000,1000,GK,10,8,...,17,58,28,10,13,46,56,55,45,53
12749,12978,M. Mansour,26,Saudi Arabia,Al Batin,30000,2000,LB,36,18,...,33,37,45,54,54,10,8,6,13,13
12767,12996,Sun Qibin,26,China PR,Tianjin Quanjian FC,20000,2000,GK,14,7,...,12,30,46,11,10,50,46,51,48,50
12861,13090,Y. Uchimura,33,Japan,Hokkaido Consadole Sapporo,20000,1000,CAM,51,31,...,33,62,45,48,42,13,15,7,15,15
12873,13102,K. Pilkington,44,England,Cambridge United,0,1000,GK,11,12,...,22,56,15,15,13,45,48,44,49,46

In [6]:
football[(football.Age < football.Age.mean())|
        (football.Club == 'FC Barcelona')]
# combination of the above example and the additional criteria

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
7,7,L. Suárez,31,Uruguay,FC Barcelona,80000000,455000,RS,77,93,...,85,85,62,45,38,27,25,31,33,37
15,15,P. Dybala,24,Argentina,Juventus,89000000,205000,LF,82,84,...,86,84,23,20,20,5,4,4,5,8
16,16,H. Kane,24,England,Tottenham Hotspur,83500000,205000,ST,75,94,...,90,89,56,36,38,8,10,11,14,11
18,18,M. ter Stegen,26,Germany,FC Barcelona,58000000,240000,GK,15,14,...,25,69,25,13,10,87,85,88,85,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12892,13121,J. Lundstram,19,England,Crewe Alexandra,1100000,1000,CM,34,38,...,43,45,40,48,47,10,13,7,8,9
12893,13122,N. Christoffersson,19,Sweden,Trelleborgs FF,60000,1000,ST,23,52,...,43,42,22,15,19,10,9,9,5,12
12894,13123,B. Worman,16,England,Cambridge United,60000,1000,ST,25,40,...,55,41,32,13,11,6,5,10,6,13
12895,13124,D. Walker-Rice,17,England,Tranmere Rovers,60000,1000,RW,44,50,...,50,46,20,25,27,14,6,14,8,9
12896,13125,G. Nugent,16,England,Tranmere Rovers,60000,1000,CM,41,34,...,33,43,40,43,50,10,15,9,12,9

In [8]:
football[(football.Age < football.Age.mean())&
        (football.Club == 'FC Barcelona')].Wage.mean()
# Here we have avg mean salary of players whose age less than mean and these players are employed by FC Barcelana.

77454.54545454546

#### 1. Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых выше среднего? Ответ округлите до сотых.

In [17]:
football[(football.Wage > football.Wage.mean())].SprintSpeed.mean()

67.56638061585058

#### 2. Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых ниже среднего? Ответ округлите до сотых.

In [18]:
football[(football.Wage < football.Wage.mean())].SprintSpeed.mean()

62.41425430560645

#### 3. Какую позицию (Position) занимает футболист с самой высокой зарплатой (Wage)?

In [33]:
football[football.Wage == football.Wage.max()].Position

0    RF
Name: Position, dtype: object

#### 4. Сколько пенальти (Penalties) забили бразильские (Nationality, Brazil) футболисты за период, данные о котором представлены в датасете?

In [36]:
football[football.Nationality == "Brazil"].Penalties.sum()

22789

### 5. Укажите средний возраст (Age) игроков, у которых точность удара головой (HeadingAccuracy) > 50.

In [37]:
football[football.HeadingAccuracy > 50].Age.mean()

25.58771113179944

### 6. Укажите возраст (Age) самого молодого игрока, у которого хладнокровие (Composure) и реакция (Reactions) превышают 90% от максимального значения, представленного в датасете.

In [46]:
football[(football.Composure > football.Composure.max()*0.9)  & (football.Reactions > football.Reactions.max()*0.9)].Age.min()

24

#### 7. Определите, насколько средняя реакция (Reactions) самых взрослых игроков (т.е. игроков, чей возраст (Age) равен максимальному) больше средней реакции самых молодых игроков. Ответ округлите до сотых.

In [54]:
meanReaction_Older = football[football.Age == football.Age.max()].Reactions.mean()
meanReaction_Young = football[football.Age == football.Age.min()].Reactions.mean()
round(meanReaction_Older-meanReaction_Young, 3)

22.643

#### 8. Из какой страны (Nationality) происходит больше всего игроков, чья стоимость (Value) превышает среднее значение?

In [67]:
football[football.Value > football.Value.mean()].Nationality.value_counts()

Spain        211
Brazil       130
France       123
Argentina    122
England      113
            ...
Moldova        1
Armenia        1
Estonia        1
Cyprus         1
Iraq           1
Name: Nationality, Length: 98, dtype: int64

#### 9. Определите, во сколько раз средняя зарплата (Wage) голкипера (Position, GK) с максимальным значением показателя " Рефлексы" (GKReflexes) выше средней зарплаты голкипера с максимальным значением показателя "Владение мячом" (GKHandling). Ответ округлите до сотых.

In [83]:
wage_1 = football[(football.Position == "GK") & (football.GKReflexes==football.GKReflexes.max())].Wage.mean()
wage_2 = football[football.GKHandling==football.GKHandling.max()].Wage.mean()
print(round(wage_1 / wage_2, 2))

2.77

#### 10. Определите, во сколько раз средняя сила удара (ShotPower) самых агрессивных игроков (игроков с максимальным значением показателя "Агрессивность" (Aggression)) выше силы удара игроков с минимальной агрессией.Ответ округлите до сотых.

In [89]:
meanShotPowerMax = football[football.Aggression == football.Aggression.max()].ShotPower.mean()
meanShotPowerMin = football[football.Aggression == football.Aggression.min()].ShotPower.mean()
print(meanShotPowerMax / meanShotPowerMin)

2.076923076923077